del /F /Q *.tmp
del /F /Q avsetting.xml
del /F /Q area.*.xml
del /F /Q bounds.xml
del /F /Q center.*.xml
del /F /Q channelorder.dat.*
del /F /Q chavsetting.xml
del /F /Q envs.xml
del /F /Q recorderlist.xml
del /F /Q reserved.*.xml
del /F /Q videorate.*.xml
del /F /Q audiorate.*.xml
del /F /Q folders.*.xml
del /F /Q encoders.*.xml
del /F /Q device.*.xml
del /F /Q dvdcompat.*.xml
del /F /Q cbitems.xml
del /F /Q channel.*.xml
del /F /Q recdefaults.*.xml
del /F /Q taiSync*.xml
del /F /Q xchapter*.xml
del /F /Q mschapter*.xml
del /F /Q mvchapter*.xml
del /F /Q chvalue*.xml
del /F /Q chtype*.xml
del /F /Q aspect*.xml
del /F /Q bvperf*.xml
del /F /Q lvoice*.xml
del /F /Q autodel.xml
del /F /Q picked.xml
del /F /Q RemoteCtrlIni.def
del /F /Q StatusView.def
del /F /Q tvrocksleepmode.txt
del /F /Q papercolors.xml
del /F /Q bscnt.*
del /F /Q makredhistory.xml
del /F /Q updatehistory.txt
del /F /Q tree_expand_*.xml
del /F /Q options_EDCB.xml
del /F /Q rs_*.xml
REM --- 3.15.4a ---
del /F /Q recorderinfolist.xml
del /F /Q papercolorsmap.xml
del /F /Q laf.txt
del /F /Q eventidmap.xml
del /F /Q cbinfolist.xml
REM --- 3.16 ---
del /F /Q chsort.xml
del /F /Q autodel*.xml
REM --- 3.16.9b ---
del /F /Q picked.txt
REM --- 3.17.4b ---
del /F /Q recorded.*.xml
REM --- 3.20 ---
del /F /Q envs.txt
del /F /Q envs.xml.bak
REM --- 3.21 ---
del /F /Q bounds.txt
del /F /Q bounds.xml.bak
REM --- 3.21.1b ---
del /F /Q _gtkrc-2.0
del /F /Q autorsv.*
